export const frases = [
  "O planejamento de hoje é a tranquilidade de amanhã.",
  "De grão em grão, construímos nossos objetivos.",
  "Trabalhando juntos pelos nossos resultados.",
  "A organização financeira é o primeiro passo para a liberdade.",
  "Pequenos hábitos diários geram grandes conquistas.",
  "O dinheiro é um meio, o nosso bem-estar é o fim.",
  "Decisões conjuntas fortalecem nossa parceria.",
  "Metas claras tornam o caminho mais fácil.",
  "Cada economia nos aproxima do que realmente importa.",
  "Transparência é a base de um bom planejamento.",
  "O futuro que queremos começa com as escolhas de hoje.",
  "Paciência e disciplina transformam números em realizações.",
  "Mais importante do que a velocidade é a constância.",
  "Cuidar do nosso dinheiro é cuidar do nosso futuro.",
  "O melhor investimento que fazemos é na nossa paz de espírito.",
  "Celebrar pequenos marcos mantém o foco na meta final.",
  "Nossos objetivos compartilhados são o nosso maior incentivo.",
  "Planejar não é sobre cortar gastos, é sobre direcionar recursos.",
  "Alinhamento financeiro é sinal de companheirismo.",
  "O controle de hoje financia a tranquilidade de amanhã.",
  "Riqueza de verdade é ter tempo para o que amamos.",
  "Um orçamento bem feito é um roteiro para as nossas metas.",
  "Construir um fundo de reserva é comprar previsibilidade.",
  "Juntos somos mais fortes frente a qualquer imprevisto.",
  "O tempo é o melhor aliado do nosso dinheiro.",
  "Evitar excessos hoje é garantir fartura no amanhã.",
  "A inteligência financeira é uma habilidade que desenvolvemos a dois.",
  "Menos impulso, mais propósito.",
  "Onde há foco, os resultados aparecem.",
  "Nossa melhor estratégia é a comunicação aberta."
];

export const versiculos = [
  "Pois onde estiver o seu tesouro, aí também estará o seu coração. - Mateus 6:21",
  "Tudo o que fizerem, façam de todo o coração. - Colossenses 3:23",
  "Consagre ao Senhor tudo o que você faz, e os seus planos serão bem-sucedidos. - Provérbios 16:3",
  "Alegrem-se na esperança, sejam pacientes na tribulação, perseverem na oração. - Romanos 12:12",
  "O amor é paciente, o amor é bondoso. - 1 Coríntios 13:4",
  "O prudente antevê o perigo e toma precauções. - Provérbios 22:3",
  "É melhor ter companhia do que estar sozinho, porque maior é a recompensa do trabalho de duas pessoas. - Eclesiastes 4:9",
  "Os planos bem elaborados levam à fartura; o apressado sempre acaba na miséria. - Provérbios 21:5",
  "Acima de tudo, guarde o seu coração, pois dele depende toda a sua vida. - Provérbios 4:23",
  "Deem graças em todas as circunstâncias. - 1 Tessalonicenses 5:18",
  "O coração do homem planeja o seu caminho, mas o Senhor lhe dirige os passos. - Provérbios 16:9",
  "Quem trabalha a sua terra terá fartura de alimento. - Provérbios 28:19",
  "O que as suas mãos tiverem que fazer, que o façam com toda a sua força. - Eclesiastes 9:10",
  "Na casa do sábio há azeite e provisões de sobra. - Provérbios 21:20",
  "Tudo tem o seu tempo determinado, e há tempo para todo propósito debaixo do céu. - Eclesiastes 3:1",
  "Honre o Senhor com todos os seus recursos e com os primeiros frutos de todas as suas plantações. - Provérbios 3:9",
  "As riquezas de origem vaidosa diminuirão, mas quem ajunta pelo trabalho terá aumento. - Provérbios 13:11",
  "Portanto, não se preocupem com o amanhã, pois o amanhã se preocupará consigo mesmo. - Mateus 6:34",
  "Sejam fortes e corajosos. Não tenham medo nem fiquem apavorados. - Deuteronômio 31:6",
  "Sejam bondosos e compassivos uns para com os outros. - Efésios 4:32",
  "Com a sabedoria se edifica a casa, e com o entendimento ela se estabelece. - Provérbios 24:3",
  "Não andem ansiosos por coisa alguma, mas em tudo, pela oração e súplicas, apresentem seus pedidos a Deus. - Filipenses 4:6",
  "A bênção do Senhor traz riqueza e não inclui dor alguma. - Provérbios 10:22",
  "Portanto, quer comais quer bebais, ou façais outra qualquer coisa, fazei tudo para glória de Deus. - 1 Coríntios 10:31",
  "Ensina-nos a contar os nossos dias para que o nosso coração alcance sabedoria. - Salmos 90:12",
  "O Senhor é o meu pastor; de nada terei falta. - Salmos 23:1",
  "A corda de três dobras não se rebenta com facilidade. - Eclesiastes 4:12",
  "Sejam humildes, pacíficos e pacientes, suportando uns aos outros com amor. - Efésios 4:2",
  "Confie no Senhor de todo o seu coração e não se apoie em seu próprio entendimento. - Provérbios 3:5",
  "Mas os que esperam no Senhor renovarão as forças, subirão com asas como águias. - Isaías 40:31"
];